version: '3'

services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - app_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge
