version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

  app:
    build: ./app
    expose:
      - "8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge