version: '3.8'

services:
  nginx:
    build: ./nginx  #custom 
    ports:
      - "80:80"    # only 1 port
    depends_on:
      - app
    networks:
      - app_network

  app:
    build: ./app
    expose:
      - "8000"     
    networks:
      - app_network
    environment:
      - FLASK_ENV=production

networks:
  app_network:
    driver: bridge