services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy

  app:
    build: ./app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/app"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  default:
    driver: bridge