services:
  nginx:
    build: ./nginx
    ports:
      - "80:80" 
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build: ./app
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/app"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  default:
    name: app_network
    driver: bridge