name: Simple Scripts Test

on: [push]

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test all bash scripts
        run: |
          cd admin/bash/
          chmod +x *.sh
          
          echo "--- Начинаем тестирование скриптов ---"
          all_passed=true
          
          for script in *.sh; do
            echo "▶ Запуск $script..."
            
            # Запускаем скрипт с тестовыми параметрами
            if ./"$script" "temp_output_$script" "5"; then
              echo "✔ $script - УСПЕХ"
            else
              echo "✖ $script - ОШИБКА (код: $?)"
              all_passed=false
              # Выводим справку по использованию
              echo "Правильное использование:"
              ./"$script" || true
            fi
            echo "--------------------------------"
          done
          
          # Завершаем с ошибкой если хотя бы один скрипт упал
          if [ "$all_passed" = false ]; then
            echo "НЕКОТОРЫЕ СКРИПТЫ ЗАВЕРШИЛИСЬ С ОШИБКОЙ"
            exit 1
          else
            echo "ВСЕ СКРИПТЫ УСПЕШНО ВЫПОЛНЕНЫ"
          fi