name: Test Bash Scripts

on: [push]

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        run: |
          cd admin/bash/
          chmod +x *.sh
          echo "Список скриптов для тестирования:"
          ls -la *.sh

      - name: Test all scripts
        id: test-scripts
        run: |
          cd admin/bash/
          total_scripts=0
          failed_scripts=0
          script_results=""
          
          for script in *.sh; do
            ((total_scripts++))
            echo "→ Тестируем $script..."
            
            # Временный файл для вывода
            output_file="${script}.output"
            
            # Запускаем скрипт с тестовыми параметрами
            if ./"$script" "test_output_${script}.txt" "5"; then
              result="✅ PASSED"
              echo "$result"
            else
              result="❌ FAILED (код $?)"
              ((failed_scripts++))
              echo "$result"
            fi
            
            script_results+="$script: $result"$'\n'
            
            # Выводим лог скрипта если он есть
            if [ -f "$output_file" ]; then
              echo "Вывод скрипта:"
              cat "$output_file"
            fi
            echo "----------------------------------------"
          done
          
          echo "Итоговый отчет:"
          echo "$script_results"
          echo "Всего скриптов: $total_scripts"
          echo "Успешно: $((total_scripts - failed_scripts))"
          echo "Неудачно: $failed_scripts"
          
          # Завершаем с ошибкой если есть хотя бы один неудачный тест
          if [ "$failed_scripts" -gt 0 ]; then
            exit 1
          fi

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: script-results
          path: admin/bash/*.output