name: Comprehensive Scripts Test

on: [push]

jobs:
  test-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare test environment
        run: |
          mkdir -p ./test_data/input/subdir{1..3}
          touch ./test_data/input/subdir1/file{1..3}
          touch ./test_data/input/subdir2/file{1..5}
          touch ./test_data/input/subdir3/file{1..2}
          mkdir -p ./test_data/output

      - name: Test all bash scripts
        run: |
          set -e
          cd admin/bash/

          chmod +x *.sh
          echo "--- Начинаем тестирование скриптов ---"

          all_passed=true

          # Задаём переменные явно, чтобы избежать проблем с вложенными путями
          INPUT_DIR="../../test_data/input"
          OUTPUT_DIR="../../test_data/output"

          declare -A test_params
          test_params["1.sh"]="output.txt 5"
          test_params["2.sh"]="$INPUT_DIR $OUTPUT_DIR"
          test_params["3.sh"]="param1 param2"
          test_params["4.sh"]="Earth"
          test_params["5.sh"]="default_param"

          for script in *.sh; do
            echo "▶ Запуск $script..."

            if [[ "$script" == "4.sh" ]]; then
              echo "Тест с правильной планетой (Earth):"
              if ./"$script" Earth | grep -q "1"; then
                echo "✔ Earth: верный результат"
              else
                echo "✖ Earth: неверный результат"
                all_passed=false
              fi

              echo "Тест с неизвестной планетой:"
              if ./"$script" Pluto 2>&1 | grep -q "Unknown planet"; then
                echo "✔ Правильно обработана неизвестная планета"
              else
                echo "✖ Не обработана неизвестная планета"
                all_passed=false
              fi

              echo "Тест без параметров:"
              if ./"$script" 2>&1 | grep -q "Unknown planet"; then
                echo "✔ Правильно обработано отсутствие параметра"
              else
                echo "✖ Не обработано отсутствие параметра"
                all_passed=false
              fi

            elif [[ -v test_params[$script] ]]; then
              echo "Аргументы: ${test_params[$script]}"
              if ./"$script" ${test_params[$script]}; then
                echo "✔ $script - УСПЕХ"
                if [[ "$script" == "2.sh" ]]; then
                  echo "Созданные файлы:"
                  ls -l "$OUTPUT_DIR"
                fi
              else
                echo "✖ $script - ОШИБКА (код: $?)"
                all_passed=false
              fi
            else
              echo "⚠ Нет тестовых параметров для $script"
              all_passed=false
            fi            
          echo "▶ 6.sh: запрещённые переменные"
          FOO=5 BAR=1 ./6.sh && {
            echo "✖ 6.sh не должен был запускаться при FOO=5 и BAR=1"
            all_passed=false
          } || echo "✔ 6.sh правильно завершён при запрещённых переменных"

          echo "▶ 6.sh: проверка появления файла fix.txt"
          touch fix.txt &
          ./6.sh && echo "✔ 6.sh обнаружил файл" || {
            echo "✖ 6.sh не обнаружил файл"
            all_passed=false
          }
          rm -f fix.txt

          echo "▶ 7.sh: анализ \$PATH"
          ./7.sh && echo "✔ 7.sh выполнен успешно" || {
            echo "✖ 7.sh завершился с ошибкой"
            all_passed=false
          }

          echo "▶ 8.sh: одна LC_ переменная"
          LC_ALL=en_US.UTF-8 ./8.sh && echo "✔ 8.sh успешен при одной LC_" || {
            echo "✖ 8.sh упал при одной LC_"
            all_passed=false
          }

          echo "▶ 8.sh: разные LC_ переменные"
          LC_ALL=en_US.UTF-8 LC_TIME=ru_RU.UTF-8 ./8.sh && {
            echo "✖ 8.sh должен был завершиться с ошибкой"
            all_passed=false
          } || echo "✔ 8.sh правильно завершён при разных LC_"

            echo "--------------------------------"
          done                  

          if [ "$all_passed" = false ]; then
            echo "НЕКОТОРЫЕ ТЕСТЫ ПРОВАЛЕНЫ"
            exit 1
          else
            echo "ВСЕ ТЕСТЫ УСПЕШНО ПРОЙДЕНЫ"
          fi

          if [ "$all_passed" = false ]; then
            echo "НЕКОТОРЫЕ ТЕСТЫ ПРОВАЛЕНЫ"
            exit 1
          else
            echo "ВСЕ ТЕСТЫ УСПЕШНО ПРОЙДЕНЫ"
          fi

      - name: Cleanup
        if: always()
        run: rm -rf ./test_data
