name: Run Bash Scripts

on: [push]

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set execute permissions
        run: |
          cd admin/bash/
          chmod +x *.sh  # Даем права на выполнение всем .sh файлам
          ls -la  # Для проверки прав

      - name: Run scripts
        run: |
          cd admin/bash/
          for script in *.sh; do
            echo "→ Running $script..."
            if ./$script; then
              echo "✅ $script executed successfully"
            else
              echo "❌ $script failed!"
              exit 1
            fi
          done